### ISSUE TITLE
Dokumentujte f-je za generisanje sudoku-a

### ISSUE THREAD

**Issue by ivan-cukic-matf** [MATF-RG17/RG098-sudoku-kocke#2]
(ako razumete kod koji ste preuzeli, ako ne, samo zatvorite ovaj issue :) )

**Comment by daviddimic** [comment]
Dokumentovao sam svoju f-ju generate_rand_sudoku koja koristi preuzet kod. Nisam se previse udubljivao u detalje preuzetog koda.
