### ISSUE TITLE
Popravite pocetnu animaciju kocke

### ISSUE THREAD

**Issue by ivan-cukic-matf** [MATF-RG17/RG098-sudoku-kocke#3]
Kocka je malo haoticna kad se pojavi na ekranu

**Comment by daviddimic** [comment]
Usporio sam kretanje kocke i promenio nacin kretanja, ne krece se linearno ka posmatracu s parametrom animacije t, vec u zavisnosti od t^2. Sto znaci da ce u pocetku kada se pojavi krece sporo, pojavljivanje vise nije haoticno, pa sve vise ubrzava ka kameri.

**Comment by ivan-cukic-matf** [comment]
I dalje na kraju skoci - animira se do jedne pozicija, pa onda skoci na zavrsnu.

**Comment by daviddimic** [comment]
Ideja je kada je pogodjena kamera da se samo pojavi u kooridnatnom pocetku, ali da to se desi prebrzo. Ispravio sam na jednostavan nacin pa sad moze da se vidi da je pogodjen pre nego sto se stavi u (0,0)
